import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import localFont from 'next/font/local'
import './globals.css'
import { Navbar } from './components/navbar'


const inter = Inter({ subsets: ['latin'] })

const font = localFont({
  src:"../public/fonts/NeueMontreal-Regular.otf",
  variable: "--font-neue"
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${font.variable}`}>
        <Navbar />
        {children}
      </body>
    </html>
  )
}
